---
name: prometheus-AD-master
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
      - pandas
      - prometheus_client
      - requests
      - boto3
      - matplotlib
      - flask
      - apscheduler
      - sortedcontainers
      - scipy
      - fbprophet
